"""Attribution and disclaimer footer — required on every page of a civic tool."""
import streamlit as st


def render_footer():
    st.divider()
    st.markdown(
        """
        <div style="text-align:center;font-size:0.8em;color:#6c757d">
        Data sourced from
        <a href="https://kenyalaw.org" target="_blank">kenyalaw.org</a> and
        <a href="https://parliament.go.ke" target="_blank">parliament.go.ke</a>
        (public domain). AI summaries and foreign law comparisons are generated by
        Claude Haiku and are provided for informational purposes only —
        refer to the official PDF for authoritative bill text.
        <strong>This platform does not provide legal advice.</strong>
        Built by <a href="https://github.com/declerke" target="_blank">@declerke</a>.
        </div>
        """,
        unsafe_allow_html=True,
    )
